# Generated by Django 4.2 on 2024-03-20 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailverificationtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
