# Generated by Django 5.0.2 on 2024-03-01 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="Blog",
        ),
    ]
