# Generated by Django 5.0.2 on 2024-03-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Views"),
        ),
    ]
