# Generated by Django 5.0.2 on 2024-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blog_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
    ]
