# Generated by Django 5.0.2 on 2024-03-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
    ]
