# Generated by Django 4.2.11 on 2024-03-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Опубликовать продукт'), ('set_category', 'Изменить категорию'), ('set_description', 'Изменить описание')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
