# Generated by Django 5.0.2 on 2024-03-11 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="indicator",
            new_name="is_active",
        ),
    ]
