# Generated by Django 5.0.2 on 2024-03-11 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_version_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="version",
            unique_together={("product", "number")},
        ),
    ]
