# Generated by Django 5.0.2 on 2024-03-11 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_version_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="номер",
            ),
        ),
    ]
