# Generated by Django 5.0.2 on 2024-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="признак"),
        ),
    ]
